spring.datasource.url=jdbc:postgresql://localhost:5432/reminder_bot_db
spring.datasource.username=Admin
spring.datasource.password=Reminder
telegram.bot.token=7736550457:AAEFs_SAnO-frBD0attUz8xim0TiffE834A
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
